config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  resources :lists do
    resources :bookmarks, only: [:new, :create, :index]
    resources :reviews, only: [:new, :create]
  end
  resources :bookmarks, only: [:destroy, :edit, :update, :show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list
  validates :comment, length: { minimum: 6 }
  validates :movie, uniqueness: { scope: :list }
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks
  has_many :reviews, dependent: :destroy
  validates :name, uniqueness: true
  validates :name, presence: true
  has_one_attached :photo
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks
  has_one :bookmark
  validates :title, :overview, uniqueness: true
  validates :title, :overview, presence: true

end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :list
  validates :rating, numericality: { only_integer: true }
  validates :rating, numericality: { in: 0..5 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  before_action :set_list, only: [:new, :create]
  def new
    @bookmark = Bookmark.new
  end

  def create
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.list = @list
    if @bookmark.save
      redirect_to list_path(@bookmark.list)
    else
      render 'lists/show', status: :unprocessable_entity
    end
  end

  def destroy
    set_bookmark
    @bookmark.destroy
    redirect_to list_path(@bookmark.list), status: :see_other
  end

  private

  def set_bookmark
    @bookmark = Bookmark.find(params[:id])
  end

  def set_list
    @list = List.find(params[:list_id])
  end

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.all
    if params[:query].present?
      @lists = List.where("name LIKE '%#{params[:query]}%'")
      @message = "You searched for #{params[:query]}, we found #{@lists.length} out of #{List.all.count} lists on our website"
    else
      @lists = List.all
    end
    @list = List.new
  end

  def show
    set_list
    @bookmark = Bookmark.new
    @review = Review.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to lists_path
    else
      redirect_to '/lists/index', status: :unprocessable_entity
    end
  end

  private

  def set_list
    @list = List.find(params[:id])
  end

  def list_params
    params.require(:list).permit(:name, :image_url, :photo)
  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def create
    @list = List.find(params[:list_id])
    @review = Review.new(review_params)
    @review.list = @list
    if @review.save
      redirect_to list_path(@review.list)
    else
      render 'lists/show', status: :unprocessable_entity
    end
  end

  private

  def review_params
    params.require(:review).permit(:comment, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://ga.jspm.io/npm:star-rating.js@4.3.0/dist/star-rating.css">
    <!-- <link href="https://cdn.jsdelivr.net/npm/tom-select@2.2.2/dist/css/tom-select.css" rel="stylesheet"> -->
    <link href="https://cdn.jsdelivr.net/npm/tom-select@2.3.1/dist/css/tom-select.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/tom-select@2.2.2/dist/css/tom-select.css" rel="stylesheet">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light py-3">
  <div class="container d-flex justify-content-between">
    <%= link_to  lists_path do %>
      <%= image_tag "popcorn_icon.png", alt: "popcorn icon", width: 50 %>
    <% end %>

    <div class='d-flex navbar-link'>
      <%= link_to lists_path do %>
        <p>All lists</p>
      <% end %>
    </div>
  </div>
</nav>

app/views/lists/index.html.erb
<%= render 'lists/navbar' %>

<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?q=80&w=3540&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D);">
  <div class="container">
    <h1>Save any kind of movies</h1>
    <p>Classic</p>
  </div>
</div>
<div class="container mb-3">
  <div class="d-flex flex-direction-column justify-content-between my-3">
      <h2 style='margin: 0;'>My lists</h2>
    <div class='d-flex'>
      <%= form_with url: lists_path, method: :get, class: "d-flex" do %>
      <%= text_field_tag :query, params[:query], class: "form-control" %>
      <%= submit_tag "search lists", class: 'btn btn-outline-success my-2 my-sm-0 mx-2' %>
      <% end %>
     <button type="button" class="btn btn-success" data-bs-toggle="modal" data-bs-target="#exampleModal">
      Create new list
    </button>
    </div>

  </div>
  <div class="cards">
  <% @lists.each do |list| %>
    <%= link_to list_path(list) do %>
      <% @image = list.image_url if list.image_url %>
      <% @image = (cl_image_path list.photo.key) if list.photo.attached? %>
      <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url( '<%= @image %>' )">
        <%= list.name %>
      </div>
    <% end %>
  <% end %>
  </div>

</div>


<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title fs-5" id="exampleModalLabel">Create a list</h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class='p-3'>
      <%= simple_form_for(@list) do |f| %>
      <%= f.input :name %>
      <%= f.input :image_url %>
      <%= f.input :photo, as: :file %>
      <%= f.submit 'create list', class: 'btn btn-success' %>
      <% end %>
      </div>
    </div>
  </div>
</div>

app/views/lists/show.html.erb
<%= render 'lists/navbar' %>
<% @image = @list.image_url if @list.image_url %>
<% @image = (cl_image_path @list.photo.key) if @list.photo.attached? %>
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(<%=@image%>);">
  <div class="container">
    <h1><%= @list.name %></h1>
  </div>
</div>

<div class="container">
  <div class='d-flex justify-content-between mt-3'>
    <h4><%= @list.bookmarks.count %> Movies</h4>
    <button type="button" class="btn btn-success" data-bs-toggle="modal" data-bs-target="#exampleModal">
      Add movie
    </button>
  </div>

  <div class="card-bookmarks mb-5 border-bottom">
    <% @list.bookmarks.each do |bookmark|%>
      <div class="card-bookmark">
        <div style="background-image: url('<%= bookmark.movie.poster_url%>')" class='bookmark-img'></div>
          <div class='bookmark-text'>
          <div>
              <div class='bookmark-title-rating'>
                <h4><%= bookmark.movie.title %></h4>
                <p><%= bookmark.movie.rating.round(1) %> ⭐️</p>
              </div>
              <p><%= bookmark.movie.overview %></p>
          </div>
            <div class="d-flex justify-content-between" style='justify-self: end;'>
              <p><i class="fa-solid fa-comment text-dark"></i> <%= bookmark.comment %></p>
              <%= link_to bookmark_path(bookmark), data: {turbo_method: :delete, turbo_confirm: "are you sure?" } do %>
                <i class="fa-solid fa-trash"></i>
              <% end %>
            </div>
          </div>
      </div>
    <% end %>
  </div>

  <div class="footer">
    <div class="review-comments">
      <h2>Reviews</h2>
      <% @list.reviews.each do |review| %>
        <div class='review-comment'>
          <p><%= content_tag :p, '⭐️' * review.rating %></p>
          <h4><%= review.comment %></h4>
        </div>
      <% end %>
    </div>
    <div class="review-form">
     <%= simple_form_for [@list, @review] do |f|%>
      <%= f.input :rating, :collection => (0..5).to_a, input_html: {data: { controller: "star-rating", action: "click->form-submit#submit"} } %>
      <%= f.input :comment %>
      <%= f.submit 'Add review', class: 'btn btn-success' %>
      <% end %>
    </div>
  </div>
</div>



<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title fs-5" id="exampleModalLabel">Add a movie</h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class='p-3'>
      <%= simple_form_for [@list, @bookmark] do |f|%>
      <%= f.input :movie_id, collection: Movie.all.order(:title), input_html: {data: {controller: "tom-select"}} %>
      <%= f.input :comment %>
      <%= f.submit 'Add movie', class: 'btn btn-success' %>
      <% end %>
      </div>
    </div>
  </div>
</div>